version: '3'

services:
  php:
    build: ./docker/php
    container_name: magentadesk-php
    image: magentadesk-php:0.0.1
    working_dir: /var/www
    command: php -S 0.0.0.0:8080
    ports:
      - 9000:8080
    volumes:
      - ./docker/php/public:/var/www
  mysql:
    build: ./docker/mysql
    container_name: magentadesk-mysql
    image: magentadesk-mysql:0.0.8
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
